name: Build debian packages

on:
  push:
    branches: "*"
    tags:
      - "*"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deb-packages:
    name: Ubuntu Devel
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: devel
    outputs:
      pkg-src-changes: ${{ env.PKG_SOURCE_CHANGES }}
      ubuntu-image: ubuntu:${{ env.UBUNTU_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build debian packages
        uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
        with:
          docker-image: ubuntu:${{ env.UBUNTU_VERSION }}
          use-gbp: 'true'

  check-modified-files:
    name: Check modified files
    runs-on: ubuntu-latest
    needs: build-deb-packages
    outputs:
      list: ${{ fromJSON(steps.git-diff.outputs.modified_files) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 100

      - name: Check modified files
        id: git-diff
        run: |
          set -ue

          base_ref=${{ github.event.pull_request.base.sha }}
          if [ -z "${base_ref}" ]; then
            base_ref=${{ github.event.before }}
          fi
          if [ -z "${base_ref}" ]; then
            base_ref=$(git log --root --reverse -n1 --format=%H)
          fi

          # Build a JSON array of modified paths.
          modified_files=$(git diff --name-only "${base_ref}" HEAD | \
            while read line; do
              jq -n --arg path "$line" '$path'
            done | jq -n '. |= [inputs]')
          echo "${modified_files}"

          escaped_json=$(echo "${modified_files}" | jq '.| tostring')
          echo "modified_files=${escaped_json}" >> "${GITHUB_OUTPUT}"

  autopkgtest:
    name: Run autopkgtests
    runs-on: ubuntu-latest
    needs:
      - build-deb-packages
      - check-modified-files
    if: ${{ github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/') ||
      contains(needs.check-modified-files.outputs.list, 'debian/tests/') ||
      contains(needs.check-modified-files.outputs.list, 'debian/gjs-check-runtime-dependencies.sh') }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Run autopkgtests
        uses: canonical/desktop-engineering/gh-actions/common/run-autopkgtest@main
        with:
          source-changes: ${{ needs.build-deb-packages.outputs.pkg-src-changes }}
          lxd-image: ${{ needs.build-deb-packages.outputs.ubuntu-image }}
